version: "3.7"
services:
  redis:
    image: redis:6.2.1
    ports:
      - "6379:6379"
  referee:
    image: armory/referee:v1.2.0
    ports:
      - "3001:3001"
    environment:
      KAYENTA_BASE_URL: http://kayenta:8090 
  kayenta:
    image: us-docker.pkg.dev/spinnaker-community/docker/kayenta:0.19.0-20201207200017
    ports:
      - "8090:8090"
    environment:
      # we inject the following 2 spring properties to make it easier
      # to deploy kayenta with a base configuration and custom, user
      # configuration. 
      SPRING_PROFILES_ACTIVE: local,user
      SPRING_CONFIG_ADDITIONAL-LOCATION: /opt/kayenta/config
      REDIS_CONNECTION: redis://redis:6379
    volumes:
      - "./config:/opt/spinnaker/config/"
  minio:
    image: minio/minio:RELEASE.2021-03-04T00-53-13Z
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  data1-1:
  data1-2: